src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: "image")]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\Column(name: "alt_text", length: 255, nullable: true)]
    private ?string $alt_text = null;

    #[ORM\Column(name: "createdAt", type: "datetime")]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\ManyToOne(targetEntity: "App\Entity\Trick", inversedBy: "images")]
    #[ORM\JoinColumn(name: "trick_id", referencedColumnName: "id", nullable: false)]
    private ?Trick $trick = null;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getAltText(): ?string
    {
        return $this->alt_text;
    }

    public function setAltText(?string $alt_text): self
    {
        $this->alt_text = $alt_text;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[ORM\Table(name: "trick")]
class Trick
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;
    
    #[ORM\Column(length: 255)]
    private ?string $slug = null;
    
    #[ORM\Column(type: "text")]
    private ?string $description = null;
    
    #[ORM\Column(name: "createdAt", type: "datetime")]
    private ?\DateTimeInterface $createdAt = null;
    
    #[ORM\Column(name: "updatedAt", type: "datetime")]
    private ?\DateTimeInterface $updatedAt = null;
    
    #[ORM\ManyToOne(targetEntity: "App\Entity\User", inversedBy: "tricks")]
    #[ORM\JoinColumn(name: "author_id", referencedColumnName: "id")]
    private ?User $author = null;
    
    #[ORM\ManyToOne(targetEntity: "App\Entity\Category", inversedBy: "tricks")]
    #[ORM\JoinColumn(name: "category_id", referencedColumnName: "id")]
    private ?Category $category = null;
    
    #[ORM\OneToMany(mappedBy: "trick", targetEntity: "App\Entity\Image", orphanRemoval: true)]
    private Collection $images;
    
    #[ORM\OneToMany(mappedBy: "trick", targetEntity: "App\Entity\Video", orphanRemoval: true)]
    private Collection $videos;
    
    #[ORM\OneToMany(mappedBy: "trick", targetEntity: "App\Entity\Comment", orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }
    
   
    public function getImageFilename(): ?string
    {
        if ($this->images->isEmpty()) {
            return null;
        }
        
        return $this->images->first()->getFilename();
    }
    
    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }
    
    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
           
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }
    
   
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Entity\Image;
use App\Entity\Video;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use App\Repository\TrickRepository;
use App\Repository\ImageRepository;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;
use App\Form\EditType;


class TrickController extends AbstractController
{
    #[Route('/trick/{slug}', name: 'app_trick_show')]
    public function show(Request $request, string $slug, TrickRepository $trickRepository, CommentRepository $commentRepository, EntityManagerInterface $entityManager): Response
    {
        $trick = $trickRepository->findOneBySlugWithRelations($slug);
        
        if (!$trick) {
            throw $this->createNotFoundException('Trick non trouvé');
        }
        
        $page = $request->query->getInt('page', 1);
        $pagerfanta = $commentRepository->findCommentsByTrick($trick, $page, 10);
        
    
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid() && $this->getUser()) {
            $comment->setTrick($trick);
            $comment->setAuthor($this->getUser());
            $comment->setCreatedAt(new \DateTime());
            
            $commentRepository->save($comment);
            
            $this->addFlash('success', 'Votre commentaire a été ajouté avec succès!');
      
            return $this->redirectToRoute('app_trick_show', ['slug' => $slug]);
        }
        
        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'commentForm' => $form->createView(),
            'pager' => $pagerfanta
        ]);
    }

    #[Route('/trick/{slug}/edit', name: 'app_trick_edit')]
    public function edit(Request $request, string $slug, TrickRepository $trickRepository, EntityManagerInterface $entityManager): Response
    {
        $trick = $trickRepository->findOneBySlugWithRelations($slug);
        
        if (!$trick) {
            throw $this->createNotFoundException('Trick non trouvé');
        }

        $form = $this->createForm(EditType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->addFlash('info', 'DEBUG: Formulaire soumis et valide'); 
            
            $imageFile = $form->get('imageFile')->getData();
            if ($imageFile) {
                $newFilename = md5(uniqid()) . '.' . $imageFile->guessExtension();
                //sécurisation du nom des fichiers, uniqid() génère un identifiant unique aléatoire, md5() génère un hash md5 unique
                //guessExtension() détermine l'extention sécurisée du fichier basé sur le type MIME
                //évite les injections de fichiers et les risques de collision entre les noms de fichiers.
                try {
                    $imageFile->move(
                        $this->getParameter('tricks_images_directory'),
                        $newFilename
                    );
                    
               
                    $image = new Image();
                    $image->setFilename($newFilename);
                    $image->setAltText($trick->getTitle());
                    $image->setTrick($trick);
                    $entityManager->persist($image);
                } catch (\Exception $e) {
                    $this->addFlash('error', 'Une erreur est survenue lors de l\'upload de l\'image');
                }
            }
  
            $videoUrl = $form->get('videoUrl')->getData();
            if ($videoUrl) {
                $video = new Video();
                $video->setUrl($videoUrl);
                $video->setTrick($trick);
          
                if (strpos($videoUrl, 'youtube') !== false || strpos($videoUrl, 'youtu.be') !== false) {
                    $video->setPlatform('youtube');
                } elseif (strpos($videoUrl, 'vimeo') !== false) {
                    $video->setPlatform('vimeo');
                } else {
                    $video->setPlatform('autre');
                }
                $entityManager->persist($video);
            }
            

            $entityManager->persist($trick);
            $entityManager->flush();
            

            $this->addFlash('success', 'Les modifications ont été enregistrées avec succès');


            return $this->redirectToRoute('app_trick_show', [
                'slug' => $trick->getSlug(),
            ]);
        }

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }
    
    #[Route('/trick/image/{id}/delete', name: 'app_image_delete', methods: ['POST'])]
    public function deleteImage(Image $image, EntityManagerInterface $entityManager, Request $request): Response
    {
        $trick = $image->getTrick();
        $slug = $trick->getSlug();
        
  
        if ($this->isCsrfTokenValid('delete'.$image->getId(), $request->request->get('_token'))) {
//le  token empêche les attaques pour supprimer des fichiers,
// empêche la suppression non autorisée des images.
            $imagePath = $this->getParameter('tricks_images_directory').'/'.$image->getFilename();
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
            
      
            $entityManager->remove($image);
            $entityManager->flush();
            
            $this->addFlash('success', 'Image supprimée avec succès');
        }

        if ($request->isXmlHttpRequest()) {
            return new JsonResponse(['success' => true]);
        }
        

        return $this->redirectToRoute('app_trick_edit', ['slug' => $slug]);
    }
    
    #[Route('/trick/video/{id}/delete', name: 'app_video_delete', methods: ['POST'])]
    public function deleteVideo(Video $video, EntityManagerInterface $entityManager, Request $request): Response
    {
        $trick = $video->getTrick();
        $slug = $trick->getSlug();
        

        if ($this->isCsrfTokenValid('delete'.$video->getId(), $request->request->get('_token'))) {
            $entityManager->remove($video);
            $entityManager->flush();
            
            $this->addFlash('success', 'Vidéo supprimée avec succès');
        }
        

        if ($request->isXmlHttpRequest()) {
            return new JsonResponse(['success' => true]);
        }
        
    
        return $this->redirectToRoute('app_trick_edit', ['slug' => $slug]);
    }

    #[Route('/trick/{slug}/delete', name: 'app_trick_delete')]
    public function delete(Request $request, string $slug, TrickRepository $trickRepository, EntityManagerInterface $entityManager): Response
    {
        $trick = $trickRepository->findOneBySlugWithRelations($slug);
        
        if (!$trick) {
            throw $this->createNotFoundException('Trick non trouvé');
        }
        
        if ($this->isCsrfTokenValid('delete'.$trick->getSlug(), $request->request->get('_token'))) {
            foreach ($trick->getImages() as $image) {
                $imagePath = $this->getParameter('tricks_images_directory').'/'.$image->getFilename();
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
            }
            
            $entityManager->remove($trick);
            $entityManager->flush();
            
            $this->addFlash('success', 'Trick supprimé avec succès');
        }

        return $this->redirectToRoute('app_home');
    }
}

templates/trick/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ trick.title }} - Snowtricks{% endblock %}

{% block body %}
<section class="container mt-5 mb-5">
    <div class="row">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header">
                    <h1 class="h3 mb-0">Modifier le trick</h1>
                </div>
                <div class="card-body">
                    <form id="edit-trick-form" method="post" action="{{ path('app_trick_edit', {'slug': trick.slug}) }}" enctype="multipart/form-data" >
                    {{ form_widget(form._token) }}
                        <div class="mb-3">
                            {{ form_row(form.title) }}
                        </div>
                        <div class="mb-3">
                            {{ form_row(form.category) }}
                        </div>
                        <div class="mb-3">
                            {{ form_row(form.description) }}
                        </div>

                        {% if trick.images|length > 0 %}
                        <div class="mb-3">
                            <h5>Images existantes</h5>-+
                            <div class="row g-3">
                                {% for image in trick.images %}
                                <div class="col-md-4 col-6">
                                    <div class="card h-100">
                                        <img src="/images/tricks/{{ image.filename }}" class="card-img-top" alt="{{ image.altText }}" style="height: 150px; object-fit: cover;">
                                        <div class="card-body">
                                            <p class="card-text small text-muted">{{ image.filename }}</p>
                                            <div class="text-end">
                                                <a href="#" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteImageModal{{ image.id }}">Supprimer</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}

                        <div class="mb-3">
                            {{ form_row(form.imageFile) }}
                            <div class="form-text">Télécharger une nouvelle image</div>
                        </div>

                        {% if trick.videos|length > 0 %}
                        <div class="mb-3">
                            <h5>Vidéos existantes</h5>
                            <div class="row g-3">
                                {% for video in trick.videos %}
                                <div class="col-md-6 mb-3">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <div class="ratio ratio-16x9 mb-3">
                                                <iframe src="{{ video.url|replace({'watch?v=': 'embed/'}) }}" allowfullscreen></iframe>
                                            </div>
                                            <p class="card-text small text-truncate text-muted">{{ video.url }}</p>
                                            <div class="text-end">
                                                <a href="#" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteVideoModal{{ video.id }}">Supprimer</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}

                        <div class="mb-3">
                            {{ form_row(form.videoUrl) }}
                            <div class="form-text">Ajouter une nouvelle vidéo (YouTube, Vimeo, etc.)</div>
                        </div>
                        
                        <div class="d-flex justify-content-between mt-4">
                            <a href="{{ path('app_trick_show', {'slug': trick.slug}) }}" class="btn btn-outline-secondary">Annuler</a>
                            <button type="submit" class="btn btn-primary" id="save-btn">Enregistrer les modifications</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% for image in trick.images %}
<div class="modal fade" id="deleteImageModal{{ image.id }}" tabindex="-1" aria-labelledby="deleteImageModalLabel{{ image.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteImageModalLabel{{ image.id }}">Confirmer la suppression</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <p>Êtes-vous sûr de vouloir supprimer cette image ?</p>
                <img src="/images/tricks/{{ image.filename }}" class="img-fluid mb-3" alt="{{ image.altText }}" style="max-height: 200px; width: auto;">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <form method="post" action="{{ path('app_image_delete', {'id': image.id}) }}" class="d-inline">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ image.id) }}">
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% for video in trick.videos %}
<div class="modal fade" id="deleteVideoModal{{ video.id }}" tabindex="-1" aria-labelledby="deleteVideoModalLabel{{ video.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteVideoModalLabel{{ video.id }}">Confirmer la suppression</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                <p>Êtes-vous sûr de vouloir supprimer cette vidéo ?</p>
                <div class="ratio ratio-16x9 mb-3">
                    <iframe src="{{ video.url|replace({'watch?v=': 'embed/'}) }}" allowfullscreen></iframe>
                </div>
                <p class="small text-muted">{{ video.url }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <form method="post" action="{{ path('app_video_delete', {'id': video.id}) }}" class="d-inline">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}